meta:
  persistent_disk: 65536

networks: (( merge ))

jobs:
  - name: docker
    templates:
      - name: docker
      - name: cf-containers-broker
    instances: 1
    resource_pool: default
    persistent_disk: (( meta.persistent_disk ))
    networks:
      - name: default
